"""Stamp local ES module URLs and assets with ?v=<build> so iOS Safari cannot mix cached files.
Writes js/build-info.js and rewrites imports in js/*.js plus index.html.
Usage: python3 tests/stamp_build.py
"""
import datetime, os, re, subprocess, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
JS = os.path.join(ROOT, 'js')


def git_sha():
    try:
        return subprocess.check_output(['git', 'rev-parse', '--short=7', 'HEAD'], cwd=ROOT, text=True).strip()
    except Exception:
        return 'unknown'


def stamp_of():
    if os.environ.get('BUILD_STAMP'):
        return os.environ['BUILD_STAMP']
    now = datetime.datetime.now(datetime.timezone.utc).strftime('%Y%m%d-%H%M')
    return f'{git_sha()}-{now}'


STAMP = stamp_of()
TIME = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%MZ')

IMPORT_RE = re.compile(
    r"""((?:from|import)\s+['"])(\./[^'"]+?\.js)(?:\?v=[^'"]*)?(['"])"""
)


def with_v(path):
    path = re.sub(r'\?v=[^\'"\s]*', '', path)
    sep = '&' if '?' in path else '?'
    return f'{path}{sep}v={STAMP}'


def stamp_js(text):
    return IMPORT_RE.sub(lambda m: f'{m.group(1)}{m.group(2)}?v={STAMP}{m.group(3)}', text)


def stamp_index(text):
    text = re.sub(r'(href=")(css/style\.css)(?:\?v=[^"]*)?(")', lambda m: f'{m.group(1)}{with_v(m.group(2))}{m.group(3)}', text)
    text = re.sub(r'(src=")(js/main\.js)(?:\?v=[^"]*)?(")', lambda m: f'{m.group(1)}{with_v(m.group(2))}{m.group(3)}', text)
    text = re.sub(
        r'"./vendor/three\.module\.js(?:\?v=[^"]*)?"',
        f'"./vendor/three.module.js?v={STAMP}"',
        text,
    )
    # Prefer exact add-on URLs with a query; drop the prefix map so Safari cannot cache an unstamped OrbitControls.
    text = re.sub(
        r'"three/addons/":\s*"./vendor/addons/"',
        '"three/addons/controls/OrbitControls.js": "./vendor/addons/controls/OrbitControls.js?v=' + STAMP + '",\n'
        '  "three/addons/environments/RoomEnvironment.js": "./vendor/addons/environments/RoomEnvironment.js?v=' + STAMP + '"',
        text,
    )
    text = re.sub(
        r'"./vendor/addons/controls/OrbitControls\.js(?:\?v=[^"]*)?"',
        f'"./vendor/addons/controls/OrbitControls.js?v={STAMP}"',
        text,
    )
    text = re.sub(
        r'"./vendor/addons/environments/RoomEnvironment\.js(?:\?v=[^"]*)?"',
        f'"./vendor/addons/environments/RoomEnvironment.js?v={STAMP}"',
        text,
    )
    return text


info = os.path.join(JS, 'build-info.js')
open(info, 'w', encoding='utf-8').write(
    '// Generated by tests/stamp_build.py. Shown in the Menu so a phone reload can be matched to a deploy.\n'
    f"export const BUILD = '{STAMP}';\n"
    f"export const BUILD_TIME = '{TIME}';\n"
)

for name in sorted(os.listdir(JS)):
    if not name.endswith('.js'):
        continue
    path = os.path.join(JS, name)
    src = open(path, encoding='utf-8').read()
    out = stamp_js(src)
    if out != src:
        open(path, 'w', encoding='utf-8').write(out)
        print('stamped', name)

idx = os.path.join(ROOT, 'index.html')
src = open(idx, encoding='utf-8').read()
out = stamp_index(src)
if out != src:
    open(idx, 'w', encoding='utf-8').write(out)
    print('stamped index.html')

print('BUILD', STAMP, TIME)
sys.stdout.flush()
